//
//  CocoaPods.swift
//  SwiftPackageAcknowledgement
//
//  Created by Luiz Barbosa on 03.06.20.
//  Copyright © 2020 Lautsprecher Teufel GmbH. All rights reserved.
//

import Foundation

struct CocoaPodsPlist: Codable {
    let preferenceSpecifiers: [Item]
    let stringsTable = "Acknowledgements"
    let title = "Acknowledgements"

    init(items: [Item]) {
        preferenceSpecifiers = [
            // Add header
            Item(title: "Acknowledgements", license: nil, footerText: "This application makes use of the following third party libraries:")
        ] + items + [
            // Add footer
            Item(title: "", license: nil, footerText: "Generated by SpmAck")
        ]
    }

    struct Item: Codable {
        let type: String = "PSGroupSpecifier"
        let title: String
        let license: String?
        let footerText: String

        enum CodingKeys: String, CodingKey {
            case type = "Type"
            case title = "Title"
            case license = "License"
            case footerText = "FooterText"
        }
    }

    enum CodingKeys: String, CodingKey {
        case preferenceSpecifiers = "PreferenceSpecifiers"
        case stringsTable = "StringsTable"
        case title = "Title"
    }
}

func saveToPList(
    fileSave: @escaping FileSave,
    encoder: @escaping Encoder<CocoaPodsPlist>,
    cocoaPods: CocoaPodsPlist,
    path: String
) -> Result<Void, GeneratePlistError> {
    encoder(cocoaPods)
        .flatMap { fileSave(path, $0) }
        .mapError(GeneratePlistError.cocoaPodsPListCannotBeEncoded)
}
